
# Several tools are pinned to "latest" to enable the idiomatic version file support. The version is managed by a version file.
[tools]
rust                        = { version = "latest", components = "llvm-tools,cargo,rustfmt,clippy", profile = "default", targets = "aarch64-apple-darwin,aarch64-unknown-linux-gnu,aarch64-pc-windows-msvc,x86_64-apple-darwin,x86_64-unknown-linux-gnu,x86_64-unknown-linux-musl,x86_64-pc-windows-msvc" }
cargo-binstall              = "1.17.9"
cargo-insta                 = "1.47.2"
"cargo:cargo-audit"         = "0.22.1"
"cargo:cargo-deny"          = "0.19.0"
"cargo:cargo-llvm-cov"      = "0.8.5"
"cargo:cargo-nextest"       = "0.9.132"
"cargo:mdbook"              = "0.5.2"
"cargo:mdbook-linkcheck"    = "0.7.7"
"cargo:mdbook-tabs"         = "0.3.4"
"cargo:mdbook-mermaid"      = "0.17.0"
"cargo:mdbook-toc"          = "0.15.3"
"cargo:mdbook-admonish"     = "1.20.0"
"cargo:mdbook-open-on-gh"   = "3.0.0"
"cargo:mdbook-i18n-helpers" = "0.4.0"
just                        = "latest"
python                      = "latest"
"cargo:cargo-outdated"      = "0.17.0"
"cargo:cargo-release"       = "1.1.2"
"cargo:cargo-auditable"     = "0.7.4"
"cargo:cargo-cyclonedx"     = "0.5.9"
"pipx:mdformat"             = { version = "1.0.0", uvx_args = "--with mdformat-gfm --with mdformat-config --with mdformat-footnote --with mdformat-front-matters --with mdformat-simple-breaks --with mdformat-web --with mdformat-wikilink --with mdformat-gfm-alerts --with mdformat-toc" }
actionlint                  = "1.7.12"
lychee                      = "0.23.0"
markdownlint-cli2           = "0.22.0"
"cargo:cargo-machete"       = "0.9.1"
"cargo:git-cliff"           = "2.12.0"
scorecard                   = "5.4.0"
"cargo:release-plz"         = "0.3.157"
"pipx:pre-commit"           = "latest"
"bun"                       = "latest"
shellcheck                  = "0.11.0"
zig                         = "0.15.2"
goreleaser                  = "2.15.2"

# Many of these settings are defaults, but we are explicit in case they change in the future and to make it clear to users what is enabled.
[settings]
activate_aggressive                 = true
idiomatic_version_file_enable_tools = [ "python", "rust", "bun" ]
env_cache                           = true
exec_auto_install                   = true
github_attestations                 = true
lockfile                            = true
pin                                 = true
slsa                                = true

[settings.npm]
package_manager = "bun"

[settings.pipx]
uvx = true
